### ISSUE TITLE
MQTT now in stock firmware

### ISSUE THREAD

**Issue by MallocArray** [oxivanisher/PyAirGradient2MQTT#1]
Just FYI, the latest official firmware from AirGradient has an MQTT option:
https://www.airgradient.com/documentation/firmwares/

You can configure the address from the Dashboard under Place>Connectivity Settings or through the local API

**Comment by oxivanisher** [comment]
This is correct and after some testing, it works. For all interested people, the topic of readings is `airgradient/readings/<SERIAL>`.
